// Generated by `nino routes:compile` — DO NOT EDIT.
declare module "@ninots/routing" {
    interface RouteRegistry {
        "contact.create": Record<never, never>;
        "contact.store": Record<never, never>;
        home: Record<never, never>;
        "users.destroy": { id: string };
        "users.index": Record<never, never>;
        "users.show": { id: string };
        "users.store": Record<never, never>;
        "users.update": { id: string };
    }
}
